version: '3'
services:
  postgres:
      container_name: postgres_container
      image: postgres:13.3
      build:
        context: ./docker/db
        dockerfile: Dockerfile
      environment:
        POSTGRES_DB: "hotel"
        POSTGRES_USER: "hoteladmin"
        POSTGRES_PASSWORD: "tgyuh980pj"
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres 
      ports:
        - "5432:5432"


  postgres_empty:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - 5433:5433

  postgres_develompent:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - 5434:5434

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

    

volumes:
  postgres: