version: '3'
services:
  postgres:
      container_name: postgres_container
      image: postgres:13.3
      build:
        context: ./db
        dockerfile: Dockerfile
      environment:
        POSTGRES_DB: "hotel"
        POSTGRES_USER: "hoteladmin"
        POSTGRES_PASSWORD: "tgyuh980pj"
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres 
      ports:
        - "5432:5432"

volumes:
  postgres: