FROM postgres:13
COPY init.sql /docker-entrypoint-initdb.d/

# ENV POSTGRES_DB "hotel"
# ENV POSTGRES_USER "hotelpguser"
# ENV POSTGRES_PASSWORD "tgyuh980pj"
# PGDATA: /data/postgres
# COPY init_content.sql /docker-entrypoint-initdb.d/

